"""empty message

Revision ID: 889a208d49d3
Revises: 4af50a62ba8e
Create Date: 2019-02-08 22:51:59.890932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889a208d49d3'
down_revision = '4af50a62ba8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatsessioncounter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messagescounter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('room', sa.String(length=1024), nullable=False),
    sa.Column('volunteer', sa.String(length=1024), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('messagescounter')
    op.drop_table('chatsessioncounter')
    # ### end Alembic commands ###
