"""empty message

Revision ID: c90a44bf1858
Revises: 40caaaa507b9
Create Date: 2019-04-26 22:47:21.520433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90a44bf1858'
down_revision = '40caaaa507b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userchatrelationship', sa.Column('volunteer_id', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userchatrelationship', 'volunteer_id')
    # ### end Alembic commands ###
